const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),{spawnSync}=require('child_process');
const fixturePassword='test-fixture-192';
const root=path.resolve(__dirname,'..'),web=fs.mkdtempSync(path.join(os.tmpdir(),'goyana-test192-'));
function build(test){const b=spawnSync('python',[path.join(root,'tools/prepare_web.py'),root,web,...(test?['--test-mode']:[])],{encoding:'utf8'});if(b.status)throw Error(b.stderr);if(test){const f=path.join(web,'goyana-v192-test-mode.js'),hash=require('crypto').createHash('sha256').update(fixturePassword).digest('hex');fs.writeFileSync(f,fs.readFileSync(f,'utf8').replace('0ddd6fd844301b89f79bb436d837b6add16e36a2541af7e9ae46a0bc195e8bdf',hash))}}
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.GOYANA_BROWSER_EXECUTABLE?{executablePath:process.env.GOYANA_BROWSER_EXECUTABLE}:{})});try{build(true);const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('url').pathToFileURL(path.join(web,'index.html')).href);await p.waitForTimeout(3300);await p.evaluate(()=>{document.getElementById('ob189').hidden=true;openPage('settings')});assert.equal(await p.locator('#st178 > #test192-menu').count(),1);await p.locator('#test192-menu button').click();assert.ok(await p.locator('#testmode192').evaluate(x=>x.classList.contains('active')));const original=await p.evaluate(()=>({plan:JSON.stringify(goyanaPlan111.plan),trial:localStorage.getItem('goyana-trial190')}));await p.locator('#test192-pass').fill('wrong');await p.locator('#test192-form button').click();await p.waitForTimeout(100);assert.equal(await p.locator('#test192-error').textContent(),'Password salah.');assert.equal(await p.evaluate(()=>GoyanaTest192.access()),null);assert.equal(await p.evaluate(()=>GoyanaAccess190.has('ai')),false);
await p.locator('#test192-pass').fill(fixturePassword);await p.locator('#test192-form button').click();await p.locator('#test192-controls').waitFor();assert.equal(await p.evaluate(()=>GoyanaAccess190.access().id),'PLATINUM');assert.equal(await p.evaluate(()=>GoyanaAccess190.has('ai')),true);await p.evaluate(()=>openPage('ai191'));assert.ok(await p.locator('#ai191').evaluate(x=>x.classList.contains('active')));console.log('PASS password rejects incorrect input and unlocks premium UI');
for(const [id,matrix] of [['PRO',[false,false,false]],['SUPER PRO',[true,false,false]],['SUPER PRO CHATBOT',[true,true,false]],['PLATINUM',[true,true,true]]]){await p.evaluate(()=>openPage('testmode192'));await p.locator('#test192-plan').selectOption(id);await p.locator('#test192-apply').click();assert.deepEqual(await p.evaluate(()=>['export','quick','ai'].map(x=>GoyanaAccess190.has(x))),matrix)}assert.deepEqual(await p.evaluate(()=>({plan:JSON.stringify(goyanaPlan111.plan),trial:localStorage.getItem('goyana-trial190')})),original);console.log('PASS package preview matrix preserves paid plan and trial');
await p.locator('#test192-exit').click();assert.equal(await p.evaluate(()=>GoyanaTest192.access()),null);assert.equal(await p.evaluate(()=>GoyanaAccess190.has('ai')),false);await p.locator('#test192-pass').fill(fixturePassword);await p.locator('#test192-form button').click();await p.locator('#test192-controls').waitFor();await p.reload();await p.waitForTimeout(3300);assert.equal(await p.evaluate(()=>GoyanaTest192.access()),null);console.log('PASS exit and restart restore original permissions');
for(const width of [320,360,390,430]){await p.setViewportSize({width,height:844});await p.evaluate(()=>{document.getElementById('ob189').hidden=true;openPage('testmode192')});assert.ok(await p.locator('#testmode192 .content').evaluate(x=>x.scrollWidth<=x.clientWidth+1))}await p.screenshot({path:'/tmp/goyana-mode-uji.png'});assert.deepEqual(errors,[]);await p.close();
build(false);assert.ok(!fs.existsSync(path.join(web,'goyana-v192-test-mode.js')));const normal=await b.newPage();await normal.goto(require('url').pathToFileURL(path.join(web,'index.html')).href);await normal.waitForTimeout(3300);assert.equal(await normal.evaluate(()=>typeof GoyanaTest192),'undefined');assert.equal(await normal.locator('#test192-menu').count(),0);assert.equal(await normal.locator('#testmode192').count(),0);assert.equal(await normal.evaluate(()=>GoyanaAccess190.has('ai')),false);console.log('PASS standard build ships no test mode menu, password script or premium unlock');}finally{await b.close();fs.rmSync(web,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exit(1)});
