// Daftar laporan (id, kategori, nama, ikon, deskripsi) sama dengan REP170 di HTML setelah patch v181.
// Dihasilkan dari index.html; mengikuti urutan tampil di aplikasi.
const reportCatalogA8 = <(String, String, String, String, String)>[
  ('omzet', 'keu', 'Omzet', '📈', 'Total nilai transaksi (tidak termasuk batal)'),
  ('arus', 'keu', 'Arus Kas', '🔄', 'Uang masuk vs uang keluar'),
  ('ptrx', 'keu', 'Pendapatan Transaksi', '💵', 'Uang yang sudah diterima dari pesanan'),
  ('metode', 'keu', 'Per Metode Bayar', '💳', 'Tunai, QRIS dan Transfer'),
  ('lain', 'keu', 'Pendapatan Lain', '🪙', 'Kas masuk di luar transaksi laundry'),
  ('keluar', 'keu', 'Pengeluaran', '🧾', 'Biaya operasional per kategori'),
  ('piutang', 'keu', 'Piutang (Belum Bayar)', '⏳', 'Pesanan yang belum dibayar pelanggan'),
  ('diskon', 'keu', 'Diskon & Promo Terpakai', '🏷️', 'Potongan yang diberikan ke pelanggan'),
  ('bulat', 'keu', 'Pembulatan', '🔢', 'Selisih pembulatan ke Rp500 terdekat'),
  ('laba', 'keu', 'Surplus Kas', '📊', 'Uang diterima dikurangi pengeluaran (basis kas)'),
  ('labaop182', 'keu', 'Laba Operasional', '📊', 'Omzet dikurangi HPP bahan dan biaya operasional'),
  ('semua', 'trx', 'Semua Transaksi', '🧺', 'Daftar pesanan lengkap dengan status'),
  ('layanan', 'trx', 'Top Layanan', '⭐', 'Layanan paling laris & menghasilkan'),
  ('durasi', 'trx', 'Per Durasi (Reguler/Express/Kilat)', '⚡', 'Perbandingan jenis durasi layanan'),
  ('status', 'trx', 'Status Pesanan', '🚦', 'Antrian, proses, siap ambil, telat'),
  ('batal', 'trx', 'Transaksi Dibatalkan', '❌', 'Pesanan yang dibatalkan & nilainya'),
  ('telat', 'trx', 'Telat Ambil', '⏰', 'Cucian siap tapi belum diambil > 7 hari'),
  ('antar', 'trx', 'Antar-Jemput', '🚚', 'Pesanan dengan layanan antar & ongkir'),
  ('ralat', 'trx', 'Ralat & Koreksi', '✎', 'Log perubahan transaksi oleh admin'),
  ('tumbuh', 'plg', 'Pertumbuhan Pelanggan', '🌱', 'Pelanggan baru per periode'),
  ('toppl', 'plg', 'Top Pelanggan', '🏆', 'Total belanja terbesar & paling sering'),
  ('lamabaru', 'plg', 'Pelanggan Baru vs Langganan', '🔁', 'Seberapa banyak pelanggan kembali'),
  ('poin', 'plg', 'Poin Member', '🎁', 'Poin yang didapat pelanggan'),
  ('pasif', 'plg', 'Pelanggan Tidak Aktif', '💤', 'Tidak order lebih dari 30 hari · cocok diberi promo'),
  ('kasbon', 'plg', 'Kasbon Pelanggan', '📒', 'Pelanggan dengan tagihan tertunda'),
  ('kinerja', 'peg', 'Kinerja Pegawai', '💪', 'Order & kg yang ditangani tiap pegawai'),
  ('presensi', 'peg', 'Rekap Presensi', '🕘', 'Kehadiran & jam masuk pegawai'),
  ('komisi', 'peg', 'Komisi & Gaji', '💼', 'Estimasi komisi Rp300/kg + gaji pokok'),
  ('kurir', 'peg', 'Kinerja Kurir', '🛵', 'Pengantaran & ongkir'),
  ('stok', 'stk', 'Stok Bahan', '🧴', 'Sisa stok & peringatan hampir habis'),
  ('pakai', 'stk', 'Pemakaian Bahan', '🫧', 'Perkiraan bahan terpakai dari berat cucian'),
  ('beli', 'stk', 'Pembelian Bahan', '🛒', 'Belanja bahan baku'),
  ('nilai', 'stk', 'Nilai Persediaan', '🏷️', 'Nilai uang stok bahan saat ini'),
  ('hpp182', 'stk', 'HPP Bahan Terpakai', '🫧', 'Biaya bahan berdasarkan resep dan produksi aktual'),
  ('jam', 'ops', 'Jam Sibuk', '🕑', 'Kapan pelanggan paling banyak datang'),
  ('hari', 'ops', 'Hari Teramai', '📅', 'Perbandingan per hari dalam seminggu'),
  ('waktu', 'ops', 'Ketepatan Waktu', '🎯', 'Pesanan selesai sebelum estimasi'),
  ('kapasitas', 'ops', 'Kapasitas & Berat', '⚖️', 'Total kg per hari vs kapasitas 60 kg'),
  ('tutup', 'ops', 'Tutup Kasir', '✅', 'Rekap kas akhir shift & selisih'),
  ('x-keu', 'exp', 'Export Keuangan', '📄', 'Pemasukan & pengeluaran (CSV / Excel)'),
  ('x-trx', 'exp', 'Export Transaksi', '📄', 'Semua pesanan beserta item'),
  ('x-plg', 'exp', 'Export Pelanggan', '📄', 'Data & total belanja pelanggan'),
  ('x-peg', 'exp', 'Export Pegawai', '📄', 'Kinerja, presensi & komisi'),
];
